# General
title: Twintigers aan Z
description: >-
  Theatergroep Twintigers aan Z uit Enschede
locale: nl_NL
tagline: >-
  Dé theatergroep voor Twentse jongeren tussen de 20 en 30

# Paths
baseurl: ''
url: "https://twintigersaanz.nl"

# Options
darkMode: true
showTags: true
showAuthors: false
showCategories: true
showSearch: false
showSharePost: false
showFavIcon: true
showComments: false
showCookieBanner: false
useExternalContactForm: true
useAnalytics: true

# Third Party / Social
email: info@twintigersaanz.nl
facebook: 'https://facebook.com/twintigersaanz'
# twitter: ''
instagram: 'https://www.instagram.com/twintigersaanz/'
formspree: https://formspree.io/f/mzboqenj
googleAnalyticsTrackingCode: G-F8KY7CY4VB
# disqusID: ''
# twitterHandle: ''
google-site-verification: 4l-e1BYeCyWync1MWfS_3Pjp-Jn54WwCyZJvLWLf7nM

# Collections
collections:
  projects:
    output: true
  category:
    output: true
  tag:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: "true"
  - scope:
      path: ""
      type: "pages"
    values:
      showInMenu: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "category"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "tag"
    values:
      layout: "tag"
  - scope:
      path: ""
    values:
      layout: "default"

# Permalinks
permalink: "/:categories/:year/:month/:day/:title/"

# Pagination
paginate: 10
paginate_path: "/news/page:num/"

# Includes
include: ["_pages"]

# Post Separator
excerpt_separator: <!--more-->

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
